name: "Discord changeloger"

on:
  pull_request_target:
    branches:
      - master
    types: [reopened]

jobs:
  send_changelog:
    if: github.event == 'pull_request'
    runs-on: ubuntu-latest
    name: A job to send a chengelog to Discord
    steps:
      - name: Send message
        uses: Kirus59/discord-changelog-action@main
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_secret: ${{ secrets.DISCORD_WEBHOOK_SECRET }}
          text: ${{ github.event.body }}
          author: ${{ github.event.user.login }}
